"""add_review_status_and_error_fields

Revision ID: 05b2ac75c5c5
Revises: e5b4b493d838
Create Date: 2026-02-10 19:58:09.792524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05b2ac75c5c5"
down_revision: Union[str, Sequence[str], None] = "e5b4b493d838"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with server_default for existing rows
    op.add_column(
        "reviews",
        sa.Column("status", sa.String(), nullable=False, server_default="success"),
    )
    op.add_column("reviews", sa.Column("error_message", sa.Text(), nullable=True))
    op.alter_column("reviews", "review_text", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "review_text", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("reviews", "error_message")
    op.drop_column("reviews", "status")
    # ### end Alembic commands ###
