"""add_llm_models

Revision ID: 1bd8d792dbef
Revises: 8c31502eaa45
Create Date: 2026-03-17 13:52:11.774707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd8d792dbef'
down_revision: Union[str, Sequence[str], None] = '8c31502eaa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('input_cost_per_million', sa.Float(), nullable=False),
    sa.Column('output_cost_per_million', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'name', name='uq_provider_model_name')
    )
    op.create_index(op.f('ix_llm_models_id'), 'llm_models', ['id'], unique=False)
    op.create_index(op.f('ix_llm_models_provider'), 'llm_models', ['provider'], unique=False)
    
    llm_models = sa.table(
        'llm_models',
        sa.column('provider', sa.String),
        sa.column('name', sa.String),
        sa.column('input_cost_per_million', sa.Float),
        sa.column('output_cost_per_million', sa.Float),
        sa.column('is_active', sa.Boolean),
    )

    op.bulk_insert(llm_models, [
        # OpenAI
        {"provider": "openai", "name": "gpt-5.2", "input_cost_per_million": 1.75, "output_cost_per_million": 14.00, "is_active": True},
        {"provider": "openai", "name": "gpt-5-mini", "input_cost_per_million": 0.25, "output_cost_per_million": 2.00, "is_active": True},
        {"provider": "openai", "name": "gpt-5-nano", "input_cost_per_million": 0.05, "output_cost_per_million": 0.40, "is_active": True},
        {"provider": "openai", "name": "gpt-5", "input_cost_per_million": 1.25, "output_cost_per_million": 10.00, "is_active": True},
        {"provider": "openai", "name": "gpt-4.1", "input_cost_per_million": 2.00, "output_cost_per_million": 8.00, "is_active": True},
        {"provider": "openai", "name": "gpt-4.1-mini", "input_cost_per_million": 0.40, "output_cost_per_million": 1.60, "is_active": True},
        {"provider": "openai", "name": "gpt-4.1-nano", "input_cost_per_million": 0.10, "output_cost_per_million": 0.40, "is_active": True},
        {"provider": "openai", "name": "gpt-4o", "input_cost_per_million": 2.50, "output_cost_per_million": 10.00, "is_active": True},
        {"provider": "openai", "name": "gpt-4o-mini", "input_cost_per_million": 0.15, "output_cost_per_million": 0.60, "is_active": True},
        {"provider": "openai", "name": "gpt-4-turbo", "input_cost_per_million": 10.00, "output_cost_per_million": 30.00, "is_active": True},
        {"provider": "openai", "name": "gpt-4", "input_cost_per_million": 30.00, "output_cost_per_million": 60.00, "is_active": True},
        {"provider": "openai", "name": "o1", "input_cost_per_million": 15.00, "output_cost_per_million": 60.00, "is_active": True},
        {"provider": "openai", "name": "o1-mini", "input_cost_per_million": 1.10, "output_cost_per_million": 4.40, "is_active": True},
        {"provider": "openai", "name": "o3", "input_cost_per_million": 2.00, "output_cost_per_million": 8.00, "is_active": True},
        {"provider": "openai", "name": "o3-mini", "input_cost_per_million": 1.10, "output_cost_per_million": 4.40, "is_active": True},
        # Gemini
        {"provider": "gemini", "name": "gemini-3-flash-preview", "input_cost_per_million": 0.50, "output_cost_per_million": 3.00, "is_active": True},
        {"provider": "gemini", "name": "gemini-2.5-flash", "input_cost_per_million": 0.30, "output_cost_per_million": 2.50, "is_active": True},
        {"provider": "gemini", "name": "gemini-2.5-flash-lite", "input_cost_per_million": 0.10, "output_cost_per_million": 0.40, "is_active": True},
        {"provider": "gemini", "name": "gemini-2.5-pro", "input_cost_per_million": 1.25, "output_cost_per_million": 10.00, "is_active": True},
        {"provider": "gemini", "name": "gemini-2.0-flash", "input_cost_per_million": 0.10, "output_cost_per_million": 0.40, "is_active": True},
        {"provider": "gemini", "name": "gemini-2.0-flash-lite", "input_cost_per_million": 0.075, "output_cost_per_million": 0.30, "is_active": True},
        # Anthropic
        {"provider": "anthropic", "name": "claude-opus-4-6", "input_cost_per_million": 5.00, "output_cost_per_million": 25.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-sonnet-4-5-20250929", "input_cost_per_million": 3.00, "output_cost_per_million": 15.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-haiku-4-5-20251001", "input_cost_per_million": 1.00, "output_cost_per_million": 5.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-opus-4-5-20251101", "input_cost_per_million": 5.00, "output_cost_per_million": 25.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-opus-4-1-20250805", "input_cost_per_million": 15.00, "output_cost_per_million": 75.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-sonnet-4-20250514", "input_cost_per_million": 3.00, "output_cost_per_million": 15.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-3-7-sonnet-20250219", "input_cost_per_million": 3.00, "output_cost_per_million": 15.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-opus-4-20250514", "input_cost_per_million": 15.00, "output_cost_per_million": 75.00, "is_active": True},
        {"provider": "anthropic", "name": "claude-3-haiku-20240307", "input_cost_per_million": 0.25, "output_cost_per_million": 1.25, "is_active": True},
    ])


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_models_provider'), table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_id'), table_name='llm_models')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
