"""add_pr_details_and_pending_review_status

Revision ID: 32901a3c5be4
Revises: 05b2ac75c5c5
Create Date: 2026-02-17 14:51:47.177511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32901a3c5be4'
down_revision: Union[str, Sequence[str], None] = '05b2ac75c5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pr_number', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('pr_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'pr_url')
    op.drop_column('reviews', 'pr_number')
    # ### end Alembic commands ###
