/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedLandingRouteImport } from './routes/_unauthenticated/landing'
import { Route as UnauthenticatedAuthErrorRouteImport } from './routes/_unauthenticated/auth-error'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteRouteImport } from './routes/_authenticated/history/route'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedHistoryReviewIdRouteImport } from './routes/_authenticated/history/$reviewId'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedLandingRoute = UnauthenticatedLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const UnauthenticatedAuthErrorRoute =
  UnauthenticatedAuthErrorRouteImport.update({
    id: '/auth-error',
    path: '/auth-error',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRouteRoute =
  AuthenticatedHistoryRouteRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoryRouteRoute,
  } as any)
const AuthenticatedHistoryReviewIdRoute =
  AuthenticatedHistoryReviewIdRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => AuthenticatedHistoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof AuthenticatedHistoryRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth-error': typeof UnauthenticatedAuthErrorRoute
  '/landing': typeof UnauthenticatedLandingRoute
  '/history/$reviewId': typeof AuthenticatedHistoryReviewIdRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth-error': typeof UnauthenticatedAuthErrorRoute
  '/landing': typeof UnauthenticatedLandingRoute
  '/history/$reviewId': typeof AuthenticatedHistoryReviewIdRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_unauthenticated/auth-error': typeof UnauthenticatedAuthErrorRoute
  '/_unauthenticated/landing': typeof UnauthenticatedLandingRoute
  '/_authenticated/history/$reviewId': typeof AuthenticatedHistoryReviewIdRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/dashboard'
    | '/settings'
    | '/auth-error'
    | '/landing'
    | '/history/$reviewId'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/auth-error'
    | '/landing'
    | '/history/$reviewId'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/history'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_unauthenticated/auth-error'
    | '/_unauthenticated/landing'
    | '/_authenticated/history/$reviewId'
    | '/_authenticated/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/landing': {
      id: '/_unauthenticated/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof UnauthenticatedLandingRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/auth-error': {
      id: '/_unauthenticated/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof UnauthenticatedAuthErrorRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedHistoryRouteRoute
    }
    '/_authenticated/history/$reviewId': {
      id: '/_authenticated/history/$reviewId'
      path: '/$reviewId'
      fullPath: '/history/$reviewId'
      preLoaderRoute: typeof AuthenticatedHistoryReviewIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRouteRoute
    }
  }
}

interface AuthenticatedHistoryRouteRouteChildren {
  AuthenticatedHistoryReviewIdRoute: typeof AuthenticatedHistoryReviewIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedHistoryRouteRouteChildren: AuthenticatedHistoryRouteRouteChildren =
  {
    AuthenticatedHistoryReviewIdRoute: AuthenticatedHistoryReviewIdRoute,
    AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  }

const AuthenticatedHistoryRouteRouteWithChildren =
  AuthenticatedHistoryRouteRoute._addFileChildren(
    AuthenticatedHistoryRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRouteRoute: typeof AuthenticatedHistoryRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRouteRoute: AuthenticatedHistoryRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedAuthErrorRoute: typeof UnauthenticatedAuthErrorRoute
  UnauthenticatedLandingRoute: typeof UnauthenticatedLandingRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedAuthErrorRoute: UnauthenticatedAuthErrorRoute,
  UnauthenticatedLandingRoute: UnauthenticatedLandingRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
